twig: 
    default_path: '%kernel.project_dir%/templates' 
    globals:  
        auteur: '%env(APP_AUTHOR)%' 
    form_themes: ['bootstrap_5_layout.html.twig'] 
when@test: 
    twig: 
        strict_variables: true 